// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yesmlotuqahbydtzqtik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inllc21sb3R1cWFoYnlkdHpxdGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDcxOTYsImV4cCI6MjA2MTQyMzE5Nn0.ZGu5pPlclU1Va5xJrEVv6pElhPhjhelrRJyjllrzoq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);